# -*- coding: utf-8 -*-
"""Case_study_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxi9iTaJiYQVIHFGLSPkuuFUkYyD3nHF
"""

!pip install pyspark

"""#Q1. Spark Initialization and Data Loading"""

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("Smart Education Analytics") \
    .getOrCreate()

print("Spark Session Created Successfully")

df = spark.read.csv(
    "/content/smart_education_single_dirty_dataset.csv",
    header=True,
    inferSchema=True
)

df.show(5)

df.printSchema()

print("Total Rows:", df.count())
print("Total Columns:", len(df.columns))

"""#Q2. RDD Implementation"""

education_rdd = df.rdd
education_rdd.take(5)

#1.Count total number of records
total_records = education_rdd.count()

print("Total Records:", total_records)

#2.# Filter students whose attendance is less than 75%
attendance_rdd = education_rdd.map(
    lambda row: (row["student_id"], row["attendance_percentage"])
)

attendance_rdd.take(5)

#3.Filter students whose attendance is less than 75%
low_attendance_rdd = attendance_rdd.filter(
    lambda x: x[1] is not None and x[1] < 75
)

low_attendance_students = low_attendance_rdd.collect()

print("Low Attendance Students:")
low_attendance_students[:10]

#4. Count low attendance students — Action
low_attendance_count = low_attendance_rdd.count()

print("Number of Students with Low Attendance:", low_attendance_count)

# 5. Select student performance label — Transformation

performance_rdd = education_rdd.map(
    lambda row: (row["student_id"], row["performance_label"])
)

performance_rdd.take(5)

#6. Count students by performance category — Transformation + Action
# Convert DataFrame to RDD
education_rdd = df.rdd

# Safely select student_id and performance_label
performance_rdd = education_rdd.map(
    lambda row: (
        row.asDict().get("student_id"),
        row.asDict().get("performance_label")
    )
)

performance_rdd.take(5)

"""#Q3. Key-Value Operations and Persistence"""

#1. Import StorageLevel
from pyspark import StorageLevel

#2. Create Key-Value RDD
# Create key-value RDD: (department, attendance_percentage)

department_attendance_rdd = df.select(
    "department",
    "attendance_percentage"
).rdd.map(
    lambda row: (row["department"], row["attendance_percentage"])
)

department_attendance_rdd.take(5)

#3. Remove Missing Values
# Remove rows where department or attendance is missing

clean_department_attendance_rdd = department_attendance_rdd.filter(
    lambda x: x[0] is not None and x[1] is not None
)

clean_department_attendance_rdd.take(5)

#4. Persistence
# Persist RDD in memory

clean_department_attendance_rdd.persist(StorageLevel.MEMORY_ONLY)

print("RDD persisted successfully")

#5. Shuffle Operation: Total Attendance by Department
# Total attendance by department

total_attendance_by_department = clean_department_attendance_rdd.reduceByKey(
    lambda a, b: a + b
)

total_attendance_by_department.collect()

#6. Average Attendance by Department
# Average attendance by department

attendance_sum_count_rdd = clean_department_attendance_rdd.mapValues(
    lambda value: (value, 1)
).reduceByKey(
    lambda a, b: (a[0] + b[0], a[1] + b[1])
)

average_attendance_by_department = attendance_sum_count_rdd.mapValues(
    lambda x: x[0] / x[1]
)

average_attendance_by_department.collect()

#7. Count Students by Department
# Count students department-wise

student_count_by_department = clean_department_attendance_rdd.mapValues(
    lambda value: 1
).reduceByKey(
    lambda a, b: a + b
)

student_count_by_department.collect()

#8. Unpersist RDD
# Remove RDD from memory after use

clean_department_attendance_rdd.unpersist()

print("RDD unpersisted successfully")

"""#Q4. Spark DataFrame Operations"""

# Check available columns
df.columns

# Select useful columns
student_df = df.select(
    "student_id",
    "student_name",
    "department",
    "semester",
    "attendance_percentage",
    "cgpa",
    "performance_label",
    "placement_status"
)

student_df.show(5)

#3. Filter operation
# Students with attendance less than 75%
low_attendance_df = student_df.filter(
    student_df.attendance_percentage < 75
)

low_attendance_df.show(10)

#4. Aggregation: Average CGPA by department
from pyspark.sql.functions import avg, count, max, min
# Department-wise average CGPA
department_cgpa_df = student_df.groupBy("department").agg(
    count("student_id").alias("total_students"),
    avg("cgpa").alias("average_cgpa"),
    max("cgpa").alias("highest_cgpa"),
    min("cgpa").alias("lowest_cgpa")
)

department_cgpa_df.show()

#5. Aggregation: Average attendance by department
# Department-wise average attendance
department_attendance_df = student_df.groupBy("department").agg(
    avg("attendance_percentage").alias("average_attendance")
)

department_attendance_df.show()

#6. Join operation
# Academic DataFrame
academic_df = df.select(
    "student_id",
    "department",
    "semester",
    "cgpa",
    "performance_label"
)

# Placement DataFrame
placement_df = df.select(
    "student_id",
    "placement_status"
)

# Join academic and placement data
joined_df = academic_df.join(
    placement_df,
    on="student_id",
    how="inner"
)

joined_df.show(10)

#7. Aggregation after join: Placement count by department
# Placement count by department
placement_by_department_df = joined_df.groupBy(
    "department",
    "placement_status"
).agg(
    count("student_id").alias("student_count")
)

placement_by_department_df.show()

#8. Sort result
# Sort departments by average CGPA
department_cgpa_df.orderBy("average_cgpa", ascending=False).show()

"""#Q5. Exploratory Data Analysis and Spark SQL"""

# Convert cleaned Spark DataFrame to Pandas
pandas_df = df_clean.toPandas()

import matplotlib.pyplot as plt

attendance_data = pandas_df.groupby("department")["attendance_percentage"].mean()

plt.figure(figsize=(8,5))
attendance_data.plot(kind="bar")
plt.title("Average Attendance by Department")
plt.xlabel("Department")
plt.ylabel("Average Attendance")
plt.xticks(rotation=45)
plt.show()

subject_data = pandas_df.groupby("subject")["total_marks"].mean()

plt.figure(figsize=(8,5))
subject_data.plot(kind="bar")
plt.title("Average Marks by Subject")
plt.xlabel("Subject")
plt.ylabel("Average Marks")
plt.xticks(rotation=45)
plt.show()

top_10 = pandas_df.sort_values(
    by=["cgpa", "total_marks"],
    ascending=False
).head(10)

plt.figure(figsize=(10,5))
plt.bar(top_10["student_name"], top_10["cgpa"])
plt.title("Top 10 Students by CGPA")
plt.xlabel("Student Name")
plt.ylabel("CGPA")
plt.xticks(rotation=45)
plt.show()

placement_data = pandas_df.groupby(["department", "placement_status"]).size().unstack()

placement_data.plot(kind="bar", figsize=(10,5))
plt.title("Placement Trends by Department")
plt.xlabel("Department")
plt.ylabel("Number of Students")
plt.xticks(rotation=45)
plt.show()

semester_data = pandas_df.groupby("semester")[["cgpa", "attendance_percentage", "total_marks"]].mean()

semester_data.plot(kind="bar", figsize=(10,5))
plt.title("Semester-wise Academic Report")
plt.xlabel("Semester")
plt.ylabel("Average Values")
plt.xticks(rotation=0)
plt.show()

"""#Spark SQL

"""

#1. Create SQL table
df_clean.createOrReplaceTempView("education")

#Attendance pattern
spark.sql("""
SELECT
    department,
    COUNT(student_id) AS total_students,
    ROUND(AVG(attendance_percentage), 2) AS average_attendance
FROM education
GROUP BY department
ORDER BY average_attendance DESC
""").show()

#Subject-wise performance
spark.sql("""
SELECT
    subject,
    COUNT(student_id) AS total_students,
    ROUND(AVG(total_marks), 2) AS average_marks,
    MAX(total_marks) AS highest_marks
FROM education
GROUP BY subject
ORDER BY average_marks DESC
""").show()

#Top-performing students
spark.sql("""
SELECT
    student_id,
    student_name,
    department,
    semester,
    cgpa,
    total_marks,
    performance_label
FROM education
ORDER BY cgpa DESC, total_marks DESC
LIMIT 10
""").show()

#Placement trends
spark.sql("""
SELECT
    department,
    placement_status,
    COUNT(student_id) AS student_count
FROM education
GROUP BY department, placement_status
ORDER BY department
""").show()

#Semester-wise academic report
spark.sql("""
SELECT
    semester,
    COUNT(student_id) AS total_students,
    ROUND(AVG(cgpa), 2) AS average_cgpa,
    ROUND(AVG(attendance_percentage), 2) AS average_attendance,
    ROUND(AVG(total_marks), 2) AS average_marks
FROM education
GROUP BY semester
ORDER BY semester
""").show()

"""#Q6. ETL Pipeline Development"""

#1. Extract Data
# Extract: Load dataset

raw_df = spark.read.csv(
    "/content/smart_education_single_dirty_dataset.csv",
    header=True,
    inferSchema=True
)

raw_df.show(5)

#2. Transform Academic Data
# Transform: Clean academic data

academic_df = raw_df.select(
    "student_id",
    "student_name",
    "department",
    "semester",
    "attendance_percentage",
    "subject",
    "internal_marks",
    "practical_marks",
    "final_exam_marks",
    "total_marks",
    "grade",
    "cgpa",
    "performance_label"
)

# Remove duplicates
academic_df = academic_df.dropDuplicates()

# Fill missing values
academic_df = academic_df.fillna({
    "attendance_percentage": 0,
    "internal_marks": 0,
    "practical_marks": 0,
    "final_exam_marks": 0,
    "total_marks": 0,
    "cgpa": 0,
    "grade": "Unknown",
    "performance_label": "Unknown"
})

academic_df.show(5)

#3. Transform Placement Data
placement_df = raw_df.select(
    "student_id",
    "student_name",
    "department",
    "cgpa",
    "technical_skill_score",
    "aptitude_score",
    "communication_score",
    "internship_completed",
    "placement_status"
)

# Remove duplicates
placement_df = placement_df.dropDuplicates()

# Fill missing values
placement_df = placement_df.fillna({
    "cgpa": 0,
    "technical_skill_score": 0,
    "aptitude_score": 0,
    "communication_score": 0,
    "internship_completed": "No",
    "placement_status": "Unknown"
})

placement_df.show(5)

#4. Join Academic and Placement Data
# Join academic and placement data

final_etl_df = academic_df.join(
    placement_df,
    on=["student_id", "student_name", "department", "cgpa"],
    how="inner"
)

final_etl_df.show(5)

#5. Load Final ETL Output
# Load: Save final cleaned ETL data

final_etl_df.write.mode("overwrite").csv(
    "output/final_education_etl_data",
    header=True
)

print("ETL pipeline completed and data saved successfully")

#6. Save Academic and Placement Data Separately
# Save academic cleaned data

academic_df.write.mode("overwrite").csv(
    "output/academic_cleaned_data",
    header=True
)

# Save placement cleaned data

placement_df.write.mode("overwrite").csv(
    "output/placement_cleaned_data",
    header=True
)

print("Academic and placement ETL data saved successfully")

"""#Q7. Machine Learning/Deep Learning Implementation"""

from pyspark.ml.feature import VectorAssembler, StringIndexer
from pyspark.ml.classification import DecisionTreeClassifier, LogisticRegression
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

#2. Select required columns
ml_df = df.select(
    "attendance_percentage",
    "login_count",
    "hours_studied_online",
    "videos_watched",
    "assignments_submitted",
    "quiz_attempts",
    "discussion_posts",
    "ai_tool_usage_count",
    "internal_marks",
    "practical_marks",
    "final_exam_marks",
    "total_marks",
    "cgpa",
    "performance_label"
)

#3. Remove missing values
ml_df = ml_df.dropna()

#4. Convert target column into numeric label
label_indexer = StringIndexer(
    inputCol="performance_label",
    outputCol="label"
)

ml_df = label_indexer.fit(ml_df).transform(ml_df)

#5. Combine features
feature_columns = [
    "attendance_percentage",
    "login_count",
    "hours_studied_online",
    "videos_watched",
    "assignments_submitted",
    "quiz_attempts",
    "discussion_posts",
    "ai_tool_usage_count",
    "internal_marks",
    "practical_marks",
    "final_exam_marks",
    "total_marks",
    "cgpa"
]

assembler = VectorAssembler(
    inputCols=feature_columns,
    outputCol="features"
)

ml_data = assembler.transform(ml_df)

#6. Split data
train_data, test_data = ml_data.randomSplit([0.8, 0.2], seed=42)

print("Training Data:", train_data.count())
print("Testing Data:", test_data.count())

#7. Train Decision Tree model
dt = DecisionTreeClassifier(
    featuresCol="features",
    labelCol="label"
)

dt_model = dt.fit(train_data)

#8. Make predictions
predictions = dt_model.transform(test_data)

predictions.select(
    "performance_label",
    "label",
    "prediction",
    "probability"
).show(10)

#9. Evaluate model
evaluator = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="accuracy"
)

accuracy = evaluator.evaluate(predictions)

print("Model Accuracy:", accuracy)

#10. Confusion Matrix
predictions.groupBy("label", "prediction").count().show()

