apiVersion: v1
kind: Service
metadata:
  name: smart-education-service

spec:
  selector:
    app: smart-education

  type: NodePort

  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088