name: Smart Education CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Project Files
        run: |
          ls
          test -f Dockerfile
          test -f Case_Study_8.ipynb
          test -f smart_education_single_dirty_dataset.csv
          test -f deployment.yaml
          test -f service.yaml

      - name: Build Docker Image
        run: |
          docker build -t smart-education-analytics:latest .

      - name: Verify Docker Image
        run: |
          docker images | grep smart-education-analytics